/**
 * M6 — the credential_version bump, as ONE reviewed SQL text for all four
 * relying parties (p77 STORY-002; specs.md §3.3 M6, §5.1).
 *
 * WHY: `users.credential_version` is the epoch a session or token carries; it
 * must rise in the SAME transaction as any local verifier change, whichever
 * writer made it (the SDK writers, a script, raw SQL). A trigger is the one
 * place every writer passes through.
 *
 * Ported-From: cadra-web@b615864c:drizzle/0133_p79_use_time_epoch.sql (trigger only)
 * Ported-From: cadra-web@b615864c:drizzle/0137_p79_flip_null_keeps_mirror.sql
 *
 * The contract — `credentialVersionBumpTriggerSql(tableName)` returns
 * idempotent SQL for `<t>_bump_credential_version_on_password_change` and
 * `<t>_bump_credential_version_trg` (BEFORE UPDATE OF password):
 *
 * - `password` changed on a `local` / `prepared` / `fenced` row →
 *   `credential_version := COALESCE(OLD.credential_version, 1) + 1`.
 * - 0137 rule: a row whose NEW authority is `connect` is left alone. Its
 *   version is the MIRROR of Connect's; the flip statement
 *   `SET credential_authority = 'connect', password = NULL, credential_version = N`
 *   keeps N. NULLing the retired verifier at the flip is not a local
 *   credential change (writers-closed refuses any non-NULL write there).
 * - An update that does not change `password` never bumps.
 *
 * For `users` the names are exactly the p79 names.
 */
import { sqlIdent } from './identifiers';

export function credentialVersionBumpTriggerSql(tableName: string): string {
  const t = sqlIdent(tableName);
  const fn = sqlIdent(`${tableName}_bump_credential_version_on_password_change`);
  const trg = sqlIdent(`${tableName}_bump_credential_version_trg`);

  return `-- p77 M6 — credential_version bump with the connect-row exemption
-- (generated by @jetdevs/core credentialVersionBumpTriggerSql; cadra-web 0133 trigger + 0137 rule).
CREATE OR REPLACE FUNCTION ${fn}()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- A connect row mirrors Connect's version; the NULLing of the retired
  -- local verifier at the flip is not a local credential change (0137).
  IF NEW."credential_authority" = 'connect' THEN
    RETURN NEW;
  END IF;
  IF NEW."password" IS DISTINCT FROM OLD."password" THEN
    NEW."credential_version" := COALESCE(OLD."credential_version", 1) + 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ${trg} ON ${t};
CREATE TRIGGER ${trg}
  BEFORE UPDATE OF "password" ON ${t}
  FOR EACH ROW
  EXECUTE FUNCTION ${fn}();
`;
}
