/**
 * M3 — one allocator, as ONE reviewed SQL text (p77 STORY-002; specs.md §3.3
 * M3, §5.1, §10 flag table: `YOBO_CONNECT_ENABLED` "closes local allocation").
 *
 * WHY in the database: with Connect enabled, Yobo Connect is the only place a
 * password-bearing identity may be born; the RP provisions Connect-born rows
 * with `password` NULL. The app stops offering local signup when the flag is
 * on, but seeds, scripts and any future insert path are writers too — so the
 * database refuses a `users` INSERT that carries a verifier while the app says
 * the flag is on.
 *
 * Ported-From: cadra-web@b615864c:drizzle/0126_p79_one_allocator.sql
 * (the idea — "no second identity allocator, enforced on the write" — and the
 * CREATE OR REPLACE / DROP TRIGGER IF EXISTS shape. cadra-web's mechanism, a
 * `user_provisioning` row required behind every binding, does not port: the
 * RPs have no provisioning table. p77 M3 keys on the flag instead, carried
 * into the database by a GUC the app sets.)
 *
 * The contract:
 * - `ONE_ALLOCATOR_GUC` = `p77.connect_enabled`. The app sets it per request
 *   (transaction scope) when `YOBO_CONNECT_ENABLED` is on:
 *   `oneAllocatorGucSql(true)` → `SELECT set_config('p77.connect_enabled', 'on', true)`.
 * - `oneAllocatorTriggerSql(tableName = 'users')` returns idempotent SQL for
 *   `<t>_one_allocator` + `<t>_one_allocator_trg` (BEFORE INSERT): when the
 *   GUC reads `on`/`true`/`1` (case-insensitive) and `NEW.password IS NOT
 *   NULL`, the INSERT is refused. Unset, empty or anything else → the flag is
 *   off and local allocation proceeds (the flag defaults off; §10). An INSERT
 *   with `password` NULL — Connect-born JIT — always proceeds.
 * - Only INSERT is covered (M3 is about allocation). Writing a verifier onto
 *   an existing row is the writers-closed trigger's business.
 */
import { sqlIdent } from './identifiers';

/** The GUC the app sets when `YOBO_CONNECT_ENABLED` is on. */
export const ONE_ALLOCATOR_GUC = 'p77.connect_enabled';

/** Grep-stable start of the allocation refusal. */
export const ONE_ALLOCATOR_ERROR_PREFIX = 'local user allocation refused: ';

/**
 * SQL that sets the one-allocator GUC. `scope: 'transaction'` (default) lasts
 * until the enclosing transaction ends — run it inside the request's
 * transaction; `'session'` lasts for the pooled connection's life.
 */
export function oneAllocatorGucSql(
  enabled: boolean,
  options: { scope?: 'transaction' | 'session' } = {},
): string {
  const isLocal = (options.scope ?? 'transaction') === 'transaction';
  return `SELECT set_config('${ONE_ALLOCATOR_GUC}', '${enabled ? 'on' : 'off'}', ${isLocal ? 'true' : 'false'})`;
}

export function oneAllocatorTriggerSql(tableName = 'users'): string {
  const t = sqlIdent(tableName);
  const fn = sqlIdent(`${tableName}_one_allocator`);
  const trg = sqlIdent(`${tableName}_one_allocator_trg`);

  return `-- p77 M3 — one allocator (generated by @jetdevs/core oneAllocatorTriggerSql; after cadra-web 0126).
CREATE OR REPLACE FUNCTION ${fn}()
RETURNS trigger AS $$
BEGIN
  IF NEW."password" IS NOT NULL
     AND lower(COALESCE(current_setting('${ONE_ALLOCATOR_GUC}', true), '')) IN ('on', 'true', '1') THEN
    RAISE EXCEPTION
      'local user allocation refused: ${ONE_ALLOCATOR_GUC} is on — Yobo Connect allocates every password-bearing identity; insert % with password NULL (p77 M3)',
      COALESCE(NEW."email"::text, '(no email)')
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ${trg} ON ${t};
CREATE TRIGGER ${trg}
  BEFORE INSERT ON ${t}
  FOR EACH ROW EXECUTE FUNCTION ${fn}();
`;
}
