/**
 * M2 — writers closed, as ONE reviewed SQL text for every relying party
 * (p77 STORY-002; specs.md §3.3 M2, §5.1, §6.1–§6.2).
 *
 * WHY in the database: the app closes each writer (the credential-write seam,
 * the owner resolver), but `users.password` has more writers than the
 * repository — seeds, scripts, raw SQL, the next repository method. A control
 * that relies on every one of them remembering is not a control, so crm and
 * yobo carry this trigger set as the second, independent enforcer; generating
 * it here means the two apps carry one text instead of two hand-copies.
 *
 * Ported-From: cadra-web@b615864c:drizzle/0127_p79_writers_closed.sql
 * Ported-From: cadra-web@b615864c:drizzle/0128_p79_writers_closed_both_sides.sql
 *
 * The contract — `writersClosedTriggerSql(tableName)` returns idempotent SQL
 * (CREATE OR REPLACE FUNCTION; DROP TRIGGER IF EXISTS … CREATE TRIGGER) that:
 *
 * 1. `<t>_refuse_local_verifier_when_closed` (0128 body): refuses any INSERT or
 *    UPDATE that writes a non-NULL `password` on a row whose authority is
 *    `fenced`/`connect` BEFORE or AFTER the statement. NULLing the verifier is
 *    allowed (the flip retires it). Error text verbatim from p79.
 * 2. `<t>_invalidate_reset_tokens_at_flip` (0127): when authority moves into
 *    `fenced`/`connect` from outside that set, deletes the row's unconsumed
 *    reset tokens (`used_at IS NULL`) in the same transaction, so a link minted
 *    while local cannot write an obsolete verifier.
 * 3. `<t>_refuse_authority_rollback` — p79's 0128 refused only `connect → *`
 *    (D8, error text verbatim). p77 widens it to the whole §6.2 table: any
 *    change of `credential_authority` that is not in `AUTHORITY_TRANSITIONS`
 *    (credential-authority.ts — the SQL list is GENERATED from that table, so
 *    the trigger and `canTransition` cannot drift) is refused, with ONE
 *    exception: the D9/M1b birth rule — a `local` row with no verifier before
 *    or after the statement, bound to a Connect subject (`connect_sub` set),
 *    may move straight to `connect`. That row has nothing to hand off; it is a
 *    Connect-born identity, which is exactly what M1b stamps in bulk and what
 *    the D9 writer stamps at every later bind. Writing the same value again is
 *    not a transition and is allowed.
 * 4. A one-time sweep of unconsumed reset tokens for rows already closed.
 *
 * Function and trigger names are `<tableName>_…`; for `users` they are exactly
 * the p79 names. The table must carry `id`, `password`,
 * `credential_authority`, `connect_sub`; the reset-token table `user_id`,
 * `used_at`.
 */
import { AUTHORITY_TRANSITIONS, type CredentialAuthority } from '../credential-authority';
import { sqlIdent, sqlLiteral } from './identifiers';

/** Grep-stable start of the password-write refusal (p79 text, verbatim). */
export const WRITERS_CLOSED_ERROR_PREFIX = 'local credential write refused for user ';

/** Grep-stable start of the `connect → *` refusal (p79 D8 text, verbatim). */
export const AUTHORITY_ROLLBACK_ERROR_PREFIX = 'credential_authority rollback refused for user ';

/** Grep-stable start of the refusal for any other move outside §6.2 (p77). */
export const AUTHORITY_TRANSITION_ERROR_PREFIX = 'credential_authority transition refused for user ';

export interface WritersClosedOptions {
  /** The reset-token table whose unconsumed rows die at the fence. Default `password_reset_tokens`. */
  resetTokensTable?: string;
}

/** The legal (from, to) pairs as a SQL row-value list, generated from the one TS table. */
function transitionPairsSql(): string {
  const pairs: string[] = [];
  for (const [from, tos] of Object.entries(AUTHORITY_TRANSITIONS) as [CredentialAuthority, readonly CredentialAuthority[]][]) {
    for (const to of tos) pairs.push(`(${sqlLiteral(from)}, ${sqlLiteral(to)})`);
  }
  return pairs.join(', ');
}

export function writersClosedTriggerSql(tableName: string, options: WritersClosedOptions = {}): string {
  const t = sqlIdent(tableName);
  const tokens = sqlIdent(options.resetTokensTable ?? 'password_reset_tokens');
  const verifierFn = sqlIdent(`${tableName}_refuse_local_verifier_when_closed`);
  const verifierTrg = sqlIdent(`${tableName}_refuse_local_verifier_when_closed_trg`);
  const tokensFn = sqlIdent(`${tableName}_invalidate_reset_tokens_at_flip`);
  const tokensTrg = sqlIdent(`${tableName}_invalidate_reset_tokens_at_flip_trg`);
  const rollbackFn = sqlIdent(`${tableName}_refuse_authority_rollback`);
  const rollbackTrg = sqlIdent(`${tableName}_refuse_authority_rollback_trg`);

  return `-- p77 M2 — writers closed (generated by @jetdevs/core writersClosedTriggerSql; ported from cadra-web 0127 + 0128).

-- 1. Refuse a local verifier when the row is closed before OR after the write (0128).
CREATE OR REPLACE FUNCTION ${verifierFn}()
RETURNS trigger AS $$
DECLARE
  closed_after  boolean := NEW."credential_authority" IN ('fenced', 'connect');
  closed_before boolean := TG_OP = 'UPDATE' AND OLD."credential_authority" IN ('fenced', 'connect');
BEGIN
  IF (closed_after OR closed_before)
     AND NEW."password" IS NOT NULL
     AND (TG_OP = 'INSERT' OR NEW."password" IS DISTINCT FROM OLD."password") THEN
    RAISE EXCEPTION
      'local credential write refused for user %: credential_authority is % (was %) — the password is not cadra-web''s to write (p79 §9/§14)',
      COALESCE(NEW."id"::text, '(new)'),
      NEW."credential_authority",
      CASE WHEN TG_OP = 'UPDATE' THEN OLD."credential_authority" ELSE '(new)' END
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ${verifierTrg} ON ${t};
CREATE TRIGGER ${verifierTrg}
  BEFORE INSERT OR UPDATE OF "password", "credential_authority" ON ${t}
  FOR EACH ROW EXECUTE FUNCTION ${verifierFn}();

-- 2. Invalidate every unconsumed reset token at the fence (0127).
CREATE OR REPLACE FUNCTION ${tokensFn}()
RETURNS trigger AS $$
BEGIN
  IF NEW."credential_authority" IN ('fenced', 'connect')
     AND OLD."credential_authority" NOT IN ('fenced', 'connect') THEN
    DELETE FROM ${tokens}
     WHERE "user_id" = NEW."id" AND "used_at" IS NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ${tokensTrg} ON ${t};
CREATE TRIGGER ${tokensTrg}
  AFTER UPDATE OF "credential_authority" ON ${t}
  FOR EACH ROW EXECUTE FUNCTION ${tokensFn}();

-- 3. Authority moves only along p77 §6.2 (0128's D8 rule, widened). The pair list
--    is generated from AUTHORITY_TRANSITIONS in @jetdevs/core credential-authority.ts.
CREATE OR REPLACE FUNCTION ${rollbackFn}()
RETURNS trigger AS $$
BEGIN
  IF NEW."credential_authority" IS NOT DISTINCT FROM OLD."credential_authority" THEN
    RETURN NEW;
  END IF;
  IF OLD."credential_authority" = 'connect' THEN
    RAISE EXCEPTION
      'credential_authority rollback refused for user %: connect → % — an activated identity never rolls back (p79 D8)',
      NEW."id", NEW."credential_authority"
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  IF (OLD."credential_authority"::text, NEW."credential_authority"::text) IN (${transitionPairsSql()}) THEN
    RETURN NEW;
  END IF;
  -- D9/M1b birth rule: a verifier-less local row bound to a Connect subject is
  -- Connect-born; it has nothing to hand off and moves straight to connect.
  IF OLD."credential_authority" = 'local' AND NEW."credential_authority" = 'connect'
     AND OLD."password" IS NULL AND NEW."password" IS NULL
     AND NEW."connect_sub" IS NOT NULL THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION
    'credential_authority transition refused for user %: % → % — not a p77 §6.2 transition',
    NEW."id", COALESCE(OLD."credential_authority"::text, 'NULL'), COALESCE(NEW."credential_authority"::text, 'NULL')
    USING ERRCODE = 'integrity_constraint_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ${rollbackTrg} ON ${t};
CREATE TRIGGER ${rollbackTrg}
  BEFORE UPDATE OF "credential_authority" ON ${t}
  FOR EACH ROW EXECUTE FUNCTION ${rollbackFn}();

-- 4. One-time sweep for rows that were already closed before this trigger existed (0127).
DELETE FROM ${tokens} tok
 USING ${t} u
 WHERE u."id" = tok."user_id"
   AND tok."used_at" IS NULL
   AND u."credential_authority" IN ('fenced', 'connect');
`;
}
