import { defineConfig } from 'tsup'

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'db/index': 'src/db/index.ts',
    'db/schema/index': 'src/db/schema/index.ts',
    'db/seeds/index': 'src/db/seeds/index.ts',
    // Modules are in modules directory
    'auth/index': 'src/modules/auth/index.ts',
    'auth/providers/index': 'src/modules/auth/providers/index.ts',
    'trpc/index': 'src/trpc/index.ts',
    'trpc/routers/index': 'src/trpc/routers/index.ts',
    'permissions/index': 'src/modules/permissions/index.ts',
    'rbac/index': 'src/modules/rbac/index.ts',
    'themes/index': 'src/modules/themes/index.ts',
    'ui/index': 'src/ui/index.ts',
    'ui/primitives/index': 'src/ui/primitives/index.ts',
    'ui/data-table/index': 'src/ui/data-table/index.ts',
    'ui/layout/index': 'src/ui/layout/index.ts',
    'ui/auth/index': 'src/ui/auth/index.ts',
    'ui/feedback/index': 'src/ui/feedback/index.ts',
    'ui/display/index': 'src/ui/display/index.ts',
    'ui/skeletons/index': 'src/ui/skeletons/index.ts',
    'ui/theme/index': 'src/ui/theme/index.ts',
    'ui/admin/index': 'src/ui/admin/index.ts',
    'hooks/index': 'src/hooks/index.ts',
    'stores/index': 'src/stores/index.ts',
    'providers/index': 'src/providers/index.ts',
    'lib/index': 'src/lib/index.ts',
    'rls/index': 'src/rls/index.ts',
    'cli/index': 'src/cli/index.ts',
    'cli/db': 'src/cli/db.ts',
    'config/index': 'src/config/index.ts',
    // API Keys module
    'api-keys/index': 'src/modules/api-keys/index.ts',
    // System Config module
    'system-config/index': 'src/modules/system-config/index.ts',
    // Users module
    'users/index': 'src/modules/users/index.ts',
    // Organizations module
    'organizations/index': 'src/modules/organizations/index.ts',
    // User-Org module
    'user-org/index': 'src/modules/user-org/index.ts',
    // Security Middleware module
    'middleware/index': 'src/middleware/index.ts',
  },
  format: ['esm'],
  dts: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    'next',
    'next-auth',
    'drizzle-orm',
    '@trpc/server',
    '@trpc/client',
    'postgres',
    'react-hook-form',
    '@radix-ui/react-dialog',
    '@radix-ui/react-dropdown-menu',
    '@radix-ui/react-label',
    '@radix-ui/react-select',
    '@radix-ui/react-slot',
    '@radix-ui/react-tabs',
    '@radix-ui/react-tooltip',
    '@radix-ui/react-checkbox',
    '@radix-ui/react-scroll-area',
    'class-variance-authority',
    'lucide-react',
    '@tanstack/react-table',
    '@tanstack/react-query',
    'libphonenumber-js',
    'zustand',
    'immer',
    '@yobolabs/framework',
  ],
})
